### ISSUE TITLE
Проблема с отображением картинки

### ISSUE THREAD

**Issue by fratule** [aristofun/rubyrush#10]
### [Классы, абстрактные и статические методы](https://rubyrush.ru/steps/static-abstract-methods.html)

Проблема с отображением картинки:

![Классы, абстрактные и статические методы](https://i.imgur.com/QsLxFsW.png)

**Comment by exclaveh** [comment]
@fratule is your problem still there? If not, close the issue.
I just went to this site and everything works for me. 
Proof - https://imgur.com/D8yZGTP.png

**Comment by fratule** [comment]
I see it fixed already.
