### ISSUE TITLE
Переменные - это указатели на объект

### ISSUE THREAD

**Issue by cuthbertnogood** [aristofun/rubyrush#11]
В примере про переменные   [rubyrush/steps/if-variables/files/variables.rb](https://github.com/aristofun/rubyrush/blob/master/steps/if-variables/files/variables.rb)
было бы хорошо добавить пример кода для понимания, что-то похожее из документации - 
[Ruby/Переменные](https://ru.wikibooks.org/wiki/Ruby/%CF%E5%F0%E5%EC%E5%ED%ED%FB%E5)
> Переменные указывают на объект
Фокус-покус:

```
girlfriend = "Татьяна"
goes_on_a_visit = girlfriend
puts girlfriend             #=> Татьяна
goes_on_a_visit[0] = "Б"    # меняем первую (номер ноль) букву у переменной-строки
puts girlfriend             #=> Батьяна
                            # На первый взгляд странно и неожиданно
```
Значение, возвращаемое первой переменной, изменилось потому, что в Ruby переменные содержат лишь ссылку на то, что вы им присваиваете.

Сами данные (объект) лежат где-то в другом месте. Ввиду этого естественно, что при прямом изменении самого объекта, на который указывает переменная, все другие переменные, указывающие на этот объект, будут возвращать изменённое значение (также будут изменяться).

Чтобы girlfriend наша осталась "Татьяна", надо в переменную занести её клон:

```
girlfriend = "Татьяна"
goes_on_a_visit = girlfriend.clone
goes_on_a_visit[0] = "М"    # Но изменили мы лишь клон. Дома в сохранности сидит настоящая:
puts girlfriend             #=> Татьяна
```
Можно создавать копии объектов ещё методом .dup. Разница между ними будет понятна позже.

Для безвредного присваивания новых значений переменным их редко приходится клонировать, ибо большинство методов делают это и так. Даже если вы просто присвоите переменной новое значение, Ruby создаст объект с новым значением и поместит в (уже существующую) переменную ссылку на тот объект:

```
goes_on_a_visit = "Аристарх"    # Создаётся новый объект, переменная переводится на него
p girlfriend                    #=> "Татьяна"
```

**Comment by aristofun** [comment]
Норм. Сделаете пуллреквест в соотв урок?

**Comment by cuthbertnogood** [comment]
Сделал PR.
