### ISSUE TITLE
Lesson №74.

### ISSUE THREAD

**Issue by SergUdo** [aristofun/rubyrush#14]
В уроке №74 ("errors-exceptions"),  в коде: <a href="http://htmlstudio.ru/%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B9-rescue/" target="_blank" title="Работа с исключениями в Ruby (1)">Работа с исключениями в Ruby (1)</a> ссылка выдает ошибку 404 Not Found.

**Comment by installero** [comment]
#15
