### ISSUE TITLE
Connection is not secure

### ISSUE THREAD

**Issue by KeyJoo** [aristofun/rubyrush#2]
# :beetle: Some pages has wrong prefix into link to images :globe_with_meridians: http://

- [ ] :boom: http/https :globe_with_meridians:
- [Check page](https://rubyrush.ru/steps/magic-ball.html "Нарушена секьюрность...")

**Comment by aristofun** [comment]
Это не стоящая сейчас внимания доработка. Отдельно перевозить будем все картинки.

**Comment by KeyJoo** [comment]
Ок.
